config/routes.rb
Rails.application.routes.draw do


  root 'home#index'

  devise_for :profiles, :controllers => {:registrations => "registrations"}

  devise_scope :profile do
    get 'signed_up', :to => 'registrations#show'
  end

  get '/error', to: 'errors#index'
  get 'privacy_policy', to: 'privacy_policy#show'
  get 'legal', to: 'legal#show'
  get 'faq', to: 'faq#show'

  resources :profiles, only: [:show, :update, :edit]  do
    get :autocomplete_tutoring_subject_name, :on => :collection
    get :autocomplete_university_name, :on => :collection
    resources :reviews, only: [:edit, :update, :index]
    resource :availability, only: [:index]
    get '/history', to: 'booking_history#index'
    resources :bookings do
      get 'confirm'
      get 'cancel'
      get 'pay'
      resources :bookings_messages, only: [:new,:create,:index]
    end
    resources :add_funds, only: [:index, :new, :create]
  end

  resources :conversations ,only: [:create, :index, :show] do
    resources :messages, only: [:create]
  end

  resources :tutoring_subjects, only: [:collection]
  resources :universities, only: [:collection]
  resource :searches, :path => '/search', only: [:show , :new]

  %w( 404 422 500 503 ).each do |code|
    match code, :to => "errors#index", :code => code, :via => :all
  end
end

app/controllers/booking_history_controller.rb
class BookingHistoryController < ApplicationController
  before_action :authenticate_profile!

  def index
    tutoring_bookings = Booking.where('tutor_profile_id = ?' , current_profile.id)
    student_bookings = Booking.where('student_profile_id = ?' , current_profile.id)

    if(tutoring_bookings != nil && tutoring_bookings.size > 1 )
      past = PastBookings.new(tutoring_bookings).call
      @past_tutoring_bookings = past.paginate(:page => params[:tutor_past_page], :per_page => 6)
    end

    if(student_bookings != nil && student_bookings.size > 1)
      past = PastBookings.new(student_bookings).call
      @past_student_bookings = past.paginate(:page => params[:student_past_page], :per_page => 6)
    end
  end
end

app/views/booking_history/_index.html.erb
<section id = "tutor_bookings">
  <div class="container relative font-alt">
    <div class = "col-md-12 col-sm-12 col-lg-12 col-xs-12">
      <% if @past_tutoring_bookings != nil then %>
        <% @past_tutoring_bookings.each do | booking | %>
          <div class = "booking">
            Time: <%= booking.datetime_formatted %>
          <%= link_to "View Booking", profile_booking_path(current_profile, booking.id), :class => " btn btn-mod btn-w  btn-round conversation_link" %>
          </div>
        <% end %>
        <%= js_will_paginate @past_tutoring_bookings ,  :param_name => 'tutor_past_page' , :params => {:format => 'js'}%>
      <% else %>
        <p> No previous bookings as a tutor </p>
      <% end %>
    </div>
  </div>
</section>

<section id = "student_bookings" class = "hidden_bookings">
  <div class="container relative font-alt">
    <div class = "col-md-12 col-sm-12 col-lg-12 col-xs-12">
      <% if @past_student_bookings != nil then %>
        <% @past_student_bookings.each do | booking | %>
          <div class = "booking">
            Time: <%= booking.datetime_formatted %>
          <%= link_to "View Booking", profile_booking_path(current_profile, booking.id), :class => " btn btn-mod btn-w  btn-round conversation_link" %>
          </div>
        <% end %>
        <%= js_will_paginate @past_student_bookings ,  :param_name => 'student_past_page' , :params => {:format => 'js'}%>
      <% else %>
        <p> No previous bookings as a student </p>
      <% end %>
    </div>
  </div>
</section>

app/views/booking_history/index.html.erb
<%= render partial: 'bookings/sub_header' %>

<section class="small-section">
  <div class="container relative">
    <div class = "col-md-12 col-sm-12 col-lg-12 col-xs-12">
      <div class="section-title col-md-8 font-alt mb-60 mb-sm-30">
        <span class= "col-md-8 col-sm-9 col-lg-8 col-xs-8">
          Past Bookings for which I am a:
        </span>
        <span class ="directly_below col-md-4 col-sm-3 col-lg-4 col-xs-4" style ="text-align: left">
          <span class = "tutor_selector" id = "tutor_selector"  ><a href="javascript:changeBookings('tutor')">Tutor</a></span>
          <span class = "student_selector unselected_bookings" id = "student_selector" ><a href="javascript:changeBookings('student')">Student</a></span>
        </span>
      </div>
    </div>
  </div>
</section>

<div id = "bookings">
  <%= render partial: 'booking_history/index' %>
</div>

app/views/booking_history/index.js.erb
$('#bookings').html("<%= escape_javascript(render :partial => 'booking_history/index' ) %>");
var tempActiveSelected = activeSelected;
activeSelected = "tutor"
changeBookings(tempActiveSelected)