config/routes.rb
Rails.application.routes.draw do


  root 'home#index'

  devise_for :profiles, :controllers => {:registrations => "registrations"}

  devise_scope :profile do
    get 'signed_up', :to => 'registrations#show'
  end

  get '/error', to: 'errors#index'
  get 'privacy_policy', to: 'privacy_policy#show'
  get 'legal', to: 'legal#show'
  get 'faq', to: 'faq#show'

  resources :profiles, only: [:show, :update, :edit]  do
    get :autocomplete_tutoring_subject_name, :on => :collection
    get :autocomplete_university_name, :on => :collection
    resources :reviews, only: [:edit, :update, :index]
    resource :availability, only: [:index]
    get '/history', to: 'booking_history#index'
    resources :bookings do
      get 'confirm'
      get 'cancel'
      get 'pay'
      resources :bookings_messages, only: [:new,:create,:index]
    end
    resources :add_funds, only: [:index, :new, :create]
  end

  resources :conversations ,only: [:create, :index, :show] do
    resources :messages, only: [:create]
  end

  resources :tutoring_subjects, only: [:collection]
  resources :universities, only: [:collection]
  resource :searches, :path => '/search', only: [:show , :new]

  %w( 404 422 500 503 ).each do |code|
    match code, :to => "errors#index", :code => code, :via => :all
  end
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base

  belongs_to :sender, :foreign_key => :sender_id, class_name: 'Profile'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'Profile'
  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  validates_presence_of(:sender)
  validates_presence_of(:recipient)

  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id, recipient_id, recipient_id, sender_id)
  end

  def other_profile(profile)
    profile == sender ? recipient : sender
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_profile!
  before_action :set_current_profile, only: [:index, :show]

  def index
    find_conversations_information
    set_message_previews
  end

  def show
    @conversation = Conversation.between(current_profile.id, params[:id]).first

    if @conversation == nil ||
        (@conversation.sender_id != current_profile.id && @conversation.recipient_id != current_profile.id)

      find_conversations_information
      @current_profile.errors.add(:id, "Invalid Conversation Selected")
      render :index

    else
      @other_profile = @conversation.sender_id == current_profile.id ? Profile.find_by(id: @conversation.recipient_id) : Profile.find_by(id: @conversation.sender_id)

      params[:limit] = params[:limit] == nil ? 15 : params[:limit]

      @messages = @conversation.messages.order('created_at desc').limit(params[:limit])

      #Is used to tell the user they can load more messages or not
      @loadedAllMessages = @messages.length == @conversation.messages.count ? true : false

      respond_to do |format|
        format.js
      end
    end
  end

  private

  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end

  def set_current_profile
    @current_profile = current_profile
  end

  def set_message_previews
    @previews = BuildMessagePreviews.new(@conversations).call
  end

  def find_conversations_information
    @conversations = Conversation.where("recipient_id = ? or sender_id = ?", current_profile.id, current_profile.id).order(latest_message: 'desc')
    @conversation_info = BuildConversationInformation.new(@conversations, current_profile).call
  end
end

app/views/conversations/_show.html.erb
<div class="top">
  <span>To: <span class="name"><%= @other_profile.first_name %></span></span>
  <% if @other_profile.active_tutor == true %>
      <div>
        <%= link_to "View Profile", profile_path(@other_profile), :class => " btn btn-mod btn-w btn-round conversation_link col-xs-12 col-sm-12 col-md-3 col-md-offset-2" %>
        <%= link_to "Book A Session", new_profile_booking_path(@other_profile), :class => " btn btn-mod btn-w btn-round conversation_link col-xs-12 col-sm-12 col-md-3" %> <!--TODO-->
      </div>
  <% end %>
</div>
<div class="chat active-chat" style="overflow-y: scroll;">
  <div class="conversation-start">
    <% if @loadedAllMessages %>
        <span>No More Messages</span>
    <% else %>
        <span onClick="loadMoreConvo()">Load More</span>
    <% end %>
  </div>
  <% @messages.reverse_each do |message, i| %>
    <% if message.profile_id == current_profile.id %>
      <div class="bubble me">
        <div class="time"><%= message.created_at.strftime("%x %H:%M:%S") %></div>
        <%= message.body %>
      </div>
    <% else %>
      <div class="bubble you">
        <div class="time"><%= message.created_at.strftime("%x %H:%M:%S") %></div>
        <%= message.body %>
      </div>
    <% end %>
  <% end %>

</div>
<div class="write">
  <input class="message_input" type="text" placeholder="Type a message here"/>
  <a href="javascript:sendMessage()" class="write-link send"></a>
</div>

app/views/conversations/index.html.erb
<div class="conversations"  style = "height: 600px;">
  <div class="wrapper">
    <div class="conversation_container">
      <div class="left col-md-4 col-sm-6 col-xs-6">

<!--    TODO This is a search bar    <div class="top">
          <input type="text"/>
          <a href="javascript:;" class="search"></a>
        </div>-->
        <ul class="people" style="overflow:scroll">
          <% @conversations.each_with_index { |conversation, i| %>
              <li class="person" data-chat="person<%= @conversation_info.profiles[i].id %>" onClick="loadConvo(<%= @conversation_info.profiles[i].id  %>,<%= conversation.id  %>)">
                <%= image_tag @conversation_info.profiles[i].avatar.url %>
                <span class="name"><%= @conversation_info.profiles[i].first_name %></span></br>
                <span class="time"><%= @conversation_info.times[i] %></span>
                <span class="preview"><%= @previews[i] %></span>
              </li>
          <% } %>
        </ul>
      </div>
      <div class="right_convo col-md-8 col-sm-6 col-xs-6">
        <div class="convo">
          <% if @conversations.empty? %>
            <h2 class="section-title font-alt mt-120 mb-sm-30">
              No Conversations
            </h2>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/conversations/show.js.erb
$(".convo").html("<%= escape_javascript(render :partial => 'conversations/show' ) %>");

$('.message_input').bind('keypress', function(e) {
  if(e.keyCode == 13){
    if(e.shiftKey) {
    } else {
      sendMessage();
    }
  }
});