config/routes.rb
Rails.application.routes.draw do


  root 'home#index'

  devise_for :profiles, :controllers => {:registrations => "registrations"}

  devise_scope :profile do
    get 'signed_up', :to => 'registrations#show'
  end

  get '/error', to: 'errors#index'
  get 'privacy_policy', to: 'privacy_policy#show'
  get 'legal', to: 'legal#show'
  get 'faq', to: 'faq#show'

  resources :profiles, only: [:show, :update, :edit]  do
    get :autocomplete_tutoring_subject_name, :on => :collection
    get :autocomplete_university_name, :on => :collection
    resources :reviews, only: [:edit, :update, :index]
    resource :availability, only: [:index]
    get '/history', to: 'booking_history#index'
    resources :bookings do
      get 'confirm'
      get 'cancel'
      get 'pay'
      resources :bookings_messages, only: [:new,:create,:index]
    end
    resources :add_funds, only: [:index, :new, :create]
  end

  resources :conversations ,only: [:create, :index, :show] do
    resources :messages, only: [:create]
  end

  resources :tutoring_subjects, only: [:collection]
  resources :universities, only: [:collection]
  resource :searches, :path => '/search', only: [:show , :new]

  %w( 404 422 500 503 ).each do |code|
    match code, :to => "errors#index", :code => code, :via => :all
  end
end

app/models/search.rb
class Search < ActiveRecord::Base
  validates :course_code, format: {with: /\A((([a-zA-Z]{1,4}[\d]{3}))|)\z/,
                                   message: "Please use up to 4 letters, followed by 3 numbers. Ie, Comp102 "}

  validate :validate_university

  def empty?
    empty_rate? && empty_media? &&
      empty_university? && empty_course_code? &&
      empty_tutoring_years? && empty_tutoring_subject?
  end

  protected

  def empty_rate?
    min_rate_cents == 0 && max_rate_cents == 100
  end

  def empty_media?
    media.delete("^0-9,").split(',').empty?
  end

  def empty_university?
    university.blank?
  end

  def empty_course_code?
    course_code.blank?
  end

  def empty_tutoring_years?
    tutoring_year.delete("^0-9,").split(',').empty?
  end

  def empty_tutoring_subject?
    tutoring_subject.blank?
  end

  def validate_university
    if university.present?
      university = University.find_by(name: self.university)
      if university == nil
        self.errors.add(:university, " contains a non-valid university. Please contact us to add yours.")
      end
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_profile!

  def new
    @search = Search.new
  end

  def show
    @search = Search.create(search_params)
    @search.course_code = search_params[:tutoring_subject] if search_params[:tutoring_subject]
    @tutors = SearchProfiles.new(current_profile.id, @search).call.paginate(:page => params[:page], :per_page => 9)

    respond_to do |format|
      format.js
    end
  end

  private

  def search_params
    params.require(:search).permit(:university, :min_rate_cents, :max_rate_cents, :course_code, :tutoring_subject,
                                   :tutoring_year => [], :media => [])
  end
end

app/views/searches/_show.html.erb
<% if @search.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@search.errors.count, "error") %> in your search:</h2>

    <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="col-md-12">
  <% @tutors.each do |tutor|
    if (tutor.id != current_profile.id) %>
  <div class="col-md-4">
    <div class="panel panel-default col-md-offset-1 col-md-11 col-sm-12 col-xs-12">
      <div class="row">
        <div class="search_name col-md-12 col-sm-3 col-xs-6">
          <%= tutor.first_name.humanize %>
          <%= "#{humanized_money_with_symbol tutor.rate} Per Hour" %>
        </div>
      </div>
      <div class="row">
        <div class="image col-md-6 col-sm-4 col-xs-6">

          <div class="col-md-12 col-sm-12 mb-sm-50 mb-xs-10" style="padding-left:0px">
            <%= image_tag tutor.avatar.url() %>
          </div>

          <div class="contact_box col-md-12 col-sm-12 mb-sm-50" style="padding-left:0px">
            <%= link_to "View profile", profile_path(tutor), class: "contact_button btn btn-mod btn-w btn-round col-xs-12 col-md-12 col-sm-12 no-side-padding" %>
            <a class="contact_button btn btn-mod btn-w btn-round col-xs-12 col-md-12 col-sm-12 no-side-padding" href="javascript:div_show('<%= tutor.first_name %>' , <%= tutor.id.to_s %>)"><%= "Message " + tutor.first_name %> </a>
          </div>

        </div>
        <div class="search_description col-md-6 col-sm-7 col-xs-6" id="wrapper">
          <%= '"' + tutor.description + '"' %>
        </div>
      </div>
    </div>
  </div>
  <% end; end %>
</div>

<% if @tutors.length == 0 %>
  <h3 class="font-alt col-xs-12 col-md-12 align-center">
    No Results
  </h3>
<% end %>

<%= js_will_paginate @tutors %>
</div>

<%= render 'messages/message' %>

app/views/searches/new.html.erb
<!-- Section -->
<section class="section pt-10">
  <div class="container relative">

    <!--TODO make the main autocomplete field search BOTH subjects and course codes-->
    <!--TODO add search button-->
    <!-- Form -->
    <%= form_for @search, url: searches_path, html: {method: :get, class: 'form-horizontal'}, :remote => true do |f| %>

        <!-- Row -->
        <div class="row">

          <!-- Col -->
          <div class="col-lg-12">

            <div class="pt-20 mb-20 mb-md-10">
              <div class="input-group input-group-lg">
                <span class="input-group-addon" id="sizing-addon1"><i class="fa fa-search"></i></span>
                <%= f.autocomplete_field :tutoring_subject, autocomplete_tutoring_subject_name_profiles_path,
                                         'class' => 'input-md form-control',
                                         'aria-describedby' => 'sizing-addon1',
                                         'data-auto-focus' => true,
                                         'data-noMatchesLabel' => 'No Subjects Found',
                                         'value' => '',
                                         'placeholder' => 'What do you want to learn? E.g. "Psychology" or "PYSC101"' %>
              </div>
            </div>

          </div>
          <!-- End Col -->

        </div>
        <!-- End Row -->

        <div id="filters" class="row">
          <!-- Divider -->
          <hr class="mt-0 mb-20 "/>
          <!-- End Divider -->

          <div class="col-lg-12">

            <div class="form-group">

              <%= f.label :university, "University", :class => 'col-sm-2 control-label' %>
              <div class="col-sm-10">
                <%= f.autocomplete_field :university, autocomplete_university_name_profiles_path,
                                         'class' => 'form-control',
                                         'data-auto-focus' => true,
                                         'data-noMatchesLabel' => 'No Subjects Found', 'value' => '' %>
              </div>

            </div>

            <div class="form-group">

              <%= f.label :level, "Level", :class => 'col-sm-2 control-label' %>
              <div class="col-sm-10">

                <%= f.collection_check_boxes :tutoring_year, TutoringYear.all, :id, :name do |b| %>
                    <div class="col-sm-3">
                      <div class="checkbox">
                        <label>
                          <%= b.check_box %> <%= b.label %>
                        </label>
                      </div>
                    </div>
                <% end %>

              </div>

            </div>

            <div class="form-group">

              <%= f.label :options, "Tutoring Style", :class => 'col-sm-2 control-label' %>
              <div class="col-sm-10">

                <%= f.collection_check_boxes :media, Medium.all, :id, :name do |b| %>
                    <div class="col-sm-3">
                      <div class="checkbox">
                        <label>
                          <%= b.check_box %> <%= b.label %>
                        </label>
                      </div>
                    </div>
                <% end %>

              </div>

            </div>

            <div class="form-group">

              <%= f.label :price_range, "Price Range (Per Hour)", :class => 'col-sm-2 control-label' %>
              <div class="col-sm-10">
                <div class="col-xs-2">
                  <h5 class="uppercase">$<span id="slider-value-lower"></span></h5>
                  <%= f.hidden_field :min_rate_cents, :value => '0' %>
                </div>
                <div class="col-xs-8">
                  <div id="price-range-slider"></div>
                </div>
                <div class="col-xs-2 price-range-right">
                  <h5 class="uppercase">$<span id="slider-value-upper"></span></h5>
                  <%= f.hidden_field :max_rate_cents, :value => '100' %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <%= f.submit "Search", class: "col-md-offset-6 col-sm-offset-5 col-xs-offset-5 submit_btn btn btn-mod btn-medium btn-round" %>
    <% end %>
    <!-- End Form -->
  </div>
  <div class="small-section">
    <div class="col-md-12" id="search_results">
    </div>
  </div>
  </div>
</section>

app/views/searches/show.js.erb
$("#search_results").html("<%= escape_javascript(render :partial => 'show' ) %>");

$(".search_description").each(function(){
  $(this).dotdotdot({
    watch: "window",
    height: 175
  });
});