config/routes.rb
Rails.application.routes.draw do


  root 'home#index'

  devise_for :profiles, :controllers => {:registrations => "registrations"}

  devise_scope :profile do
    get 'signed_up', :to => 'registrations#show'
  end

  get '/error', to: 'errors#index'
  get 'privacy_policy', to: 'privacy_policy#show'
  get 'legal', to: 'legal#show'
  get 'faq', to: 'faq#show'

  resources :profiles, only: [:show, :update, :edit]  do
    get :autocomplete_tutoring_subject_name, :on => :collection
    get :autocomplete_university_name, :on => :collection
    resources :reviews, only: [:edit, :update, :index]
    resource :availability, only: [:index]
    get '/history', to: 'booking_history#index'
    resources :bookings do
      get 'confirm'
      get 'cancel'
      get 'pay'
      resources :bookings_messages, only: [:new,:create,:index]
    end
    resources :add_funds, only: [:index, :new, :create]
  end

  resources :conversations ,only: [:create, :index, :show] do
    resources :messages, only: [:create]
  end

  resources :tutoring_subjects, only: [:collection]
  resources :universities, only: [:collection]
  resource :searches, :path => '/search', only: [:show , :new]

  %w( 404 422 500 503 ).each do |code|
    match code, :to => "errors#index", :code => code, :via => :all
  end
end

app/views/common/private/_footer.html.erb
<!-- Footer -->
<footer class="page-section footer">
  <div class="container">


    <!-- <div class="footer-social-links mb-110 mb-xs-60">
      <a href="#" title="Facebook" target="_blank"><i class="fa fa-facebook"></i></a>
      <a href="#" title="Twitter" target="_blank"><i class="fa fa-twitter"></i></a>
      <a href="#" title="Instagram" target="_blank"><i class="fa fa-instagram"></i></a>
      </div> -->

      <div class="row">

        <div class="col-md-12">
          <!-- Footer Text -->
          <div class="footer-text">
            <div class="row font-alt">
              <div class="col-md-4">
                <span>Contact Us at support@tutrme.co</span>
              </div>
              <div class="col-md-4 col-md-offset-4">
                <div>
                  <%= link_to 'FAQ', faq_path %>
                  <%= link_to 'Legal', legal_path, style: "padding-left:20px; padding-right:20px;" %>
                  <%= link_to 'Privacy Policy', privacy_policy_path %>
                </div>
              </div>
            </div>
            <div class="row col-md-4 col-md-offset-4">
              <%= embedded_svg "wellington.svg" %>
              <!-- Copyright -->
              <div class="footer-copy font-alt">
                <a href="/"> &copy; TUTRME <span id="year-copy"></span></a>
              </div>
              <!-- End Copyright -->

              <div class="footer-made">
                Crafted in Wellington, NZ
              </div>
            </div>
          </div>
          <!-- End Footer Text -->
        </div>
      </div>
  </div>

  <!-- Top Link -->
  <!--<div class="local-scroll">-->
  <!--<a href="#top" class="link-to-top"><i class="fa fa-caret-up"></i></a>-->
  <!--</div>-->
  <!-- End Top Link -->

</footer>
<!-- End Footer -->

app/views/common/private/_header.html.erb
<!-- Navigation panel -->
<nav class="main-nav js-stick">
  <div class="full-wrapper relative clearfix">
    <!-- Logo ( * your text or image into link tag *) -->
    <div class="nav-logo-wrap local-scroll">

      <%= link_to 'TUTRME.', root_path, :class => 'logo' %>

    </div>
    <div class="mobile-nav">
      <i class="fa fa-bars"></i>
    </div>

    <!-- Main Menu -->
    <div class="inner-nav desktop-nav">
      <ul class="clearlist">

        <!-- Item -->
        <li>
          <%= active_link_to 'Home', root_path, :active => :exclusive %>
        </li>
        <!-- End Item -->

        <!-- Item -->
        <li>
          <%= active_link_to 'Search', new_searches_path  %>
        </li>
        <!-- End Item -->

        <li>
          <%= active_link_to 'Bookings', profile_bookings_path(current_profile) %>
        </li>

        <li>
          <%= active_link_to 'Funds', profile_add_funds_path(current_profile) %>
        </li>

        <!-- Item -->
        <li>
          <%= active_link_to 'Profile', profile_path(current_profile) %>
        </li>

        <!-- Item -->
        <li>
          <%= active_link_to 'Messages', conversations_path %>
        </li>

        <!-- Item -->
        <li>
          <%= active_link_to 'Logout', destroy_profile_session_path, :method => :delete %>
        </li>
        <!-- End Item -->
        
      </ul>
    </div>
    <!-- End Main Menu -->


  </div>
</nav>
<!-- End Navigation panel -->